# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Tests package."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import TYPE_CHECKING

from flext_core.lazy import install_lazy_exports

if TYPE_CHECKING:
    from tests import (
        conftest as conftest,
        constants as constants,
        e2e as e2e,
        models as models,
        protocols as protocols,
        typings as typings,
        unit as unit,
        utilities as utilities,
    )
    from tests.conftest import (
        MockLdapConnection as MockLdapConnection,
        MockLdapDbtAdapter as MockLdapDbtAdapter,
        dbt_ldap_macros as dbt_ldap_macros,
        dbt_ldap_models as dbt_ldap_models,
        dbt_ldap_profile as dbt_ldap_profile,
        dbt_ldap_project_config as dbt_ldap_project_config,
        dbt_ldap_sources as dbt_ldap_sources,
        dbt_ldap_tests as dbt_ldap_tests,
        ldap_performance_config as ldap_performance_config,
        ldap_source_config as ldap_source_config,
        ldap_validation_rules as ldap_validation_rules,
        mock_ldap_connection as mock_ldap_connection,
        mock_ldap_dbt_adapter as mock_ldap_dbt_adapter,
        pytest_configure as pytest_configure,
        sample_ldap_entries as sample_ldap_entries,
        set_test_environment as set_test_environment,
        shared_ldap_config as shared_ldap_config,
        shared_ldap_container as shared_ldap_container,
    )
    from tests.constants import (
        FlextDbtLdapTestConstants as FlextDbtLdapTestConstants,
        FlextDbtLdapTestConstants as c,
    )
    from tests.e2e.conftest import (
        POSTGRES_READY_MAX_RETRIES as POSTGRES_READY_MAX_RETRIES,
        count_rows as count_rows,
        db_connection as db_connection,
        dbt_profiles_dir as dbt_profiles_dir,
        dbt_project_dir as dbt_project_dir,
        flext_docker as flext_docker,
        get_column_names as get_column_names,
        logger as logger,
        postgres_container as postgres_container,
        project_root as project_root,
        psycopg as psycopg,
        query_database as query_database,
        run_dbt_command as run_dbt_command,
        sql as sql,
        table_exists as table_exists,
    )
    from tests.models import (
        FlextDbtLdapTestModels as FlextDbtLdapTestModels,
        FlextDbtLdapTestModels as m,
    )
    from tests.protocols import (
        FlextDbtLdapTestProtocols as FlextDbtLdapTestProtocols,
        FlextDbtLdapTestProtocols as p,
    )
    from tests.typings import (
        FlextDbtLdapTestTypes as FlextDbtLdapTestTypes,
        FlextDbtLdapTestTypes as t,
    )
    from tests.unit import (
        test_dbt_services_sync as test_dbt_services_sync,
        test_version as test_version,
    )
    from tests.unit.test_dbt_services_sync import (
        test_sync_users_uses_incremental_bookmark_and_persists_state as test_sync_users_uses_incremental_bookmark_and_persists_state,
    )
    from tests.unit.test_version import (
        test_dunder_alignment as test_dunder_alignment,
        test_incremental_groups_sync_applies_bookmark_filter as test_incremental_groups_sync_applies_bookmark_filter,
        test_incremental_users_sync_applies_bookmark_filter as test_incremental_users_sync_applies_bookmark_filter,
        test_version_metadata_integrity as test_version_metadata_integrity,
        test_version_properties as test_version_properties,
    )
    from tests.utilities import (
        FlextDbtLdapTestUtilities as FlextDbtLdapTestUtilities,
        FlextDbtLdapTestUtilities as u,
    )

_LAZY_IMPORTS: Mapping[str, Sequence[str]] = {
    "FlextDbtLdapTestConstants": ["tests.constants", "FlextDbtLdapTestConstants"],
    "FlextDbtLdapTestModels": ["tests.models", "FlextDbtLdapTestModels"],
    "FlextDbtLdapTestProtocols": ["tests.protocols", "FlextDbtLdapTestProtocols"],
    "FlextDbtLdapTestTypes": ["tests.typings", "FlextDbtLdapTestTypes"],
    "FlextDbtLdapTestUtilities": ["tests.utilities", "FlextDbtLdapTestUtilities"],
    "MockLdapConnection": ["tests.conftest", "MockLdapConnection"],
    "MockLdapDbtAdapter": ["tests.conftest", "MockLdapDbtAdapter"],
    "POSTGRES_READY_MAX_RETRIES": ["tests.e2e.conftest", "POSTGRES_READY_MAX_RETRIES"],
    "c": ["tests.constants", "FlextDbtLdapTestConstants"],
    "conftest": ["tests.conftest", ""],
    "constants": ["tests.constants", ""],
    "count_rows": ["tests.e2e.conftest", "count_rows"],
    "d": ["flext_tests", "d"],
    "db_connection": ["tests.e2e.conftest", "db_connection"],
    "dbt_ldap_macros": ["tests.conftest", "dbt_ldap_macros"],
    "dbt_ldap_models": ["tests.conftest", "dbt_ldap_models"],
    "dbt_ldap_profile": ["tests.conftest", "dbt_ldap_profile"],
    "dbt_ldap_project_config": ["tests.conftest", "dbt_ldap_project_config"],
    "dbt_ldap_sources": ["tests.conftest", "dbt_ldap_sources"],
    "dbt_ldap_tests": ["tests.conftest", "dbt_ldap_tests"],
    "dbt_profiles_dir": ["tests.e2e.conftest", "dbt_profiles_dir"],
    "dbt_project_dir": ["tests.e2e.conftest", "dbt_project_dir"],
    "e": ["flext_tests", "e"],
    "e2e": ["tests.e2e", ""],
    "flext_docker": ["tests.e2e.conftest", "flext_docker"],
    "get_column_names": ["tests.e2e.conftest", "get_column_names"],
    "h": ["flext_tests", "h"],
    "ldap_performance_config": ["tests.conftest", "ldap_performance_config"],
    "ldap_source_config": ["tests.conftest", "ldap_source_config"],
    "ldap_validation_rules": ["tests.conftest", "ldap_validation_rules"],
    "logger": ["tests.e2e.conftest", "logger"],
    "m": ["tests.models", "FlextDbtLdapTestModels"],
    "mock_ldap_connection": ["tests.conftest", "mock_ldap_connection"],
    "mock_ldap_dbt_adapter": ["tests.conftest", "mock_ldap_dbt_adapter"],
    "models": ["tests.models", ""],
    "p": ["tests.protocols", "FlextDbtLdapTestProtocols"],
    "postgres_container": ["tests.e2e.conftest", "postgres_container"],
    "project_root": ["tests.e2e.conftest", "project_root"],
    "protocols": ["tests.protocols", ""],
    "psycopg": ["tests.e2e.conftest", "psycopg"],
    "pytest_configure": ["tests.conftest", "pytest_configure"],
    "query_database": ["tests.e2e.conftest", "query_database"],
    "r": ["flext_tests", "r"],
    "run_dbt_command": ["tests.e2e.conftest", "run_dbt_command"],
    "s": ["flext_tests", "s"],
    "sample_ldap_entries": ["tests.conftest", "sample_ldap_entries"],
    "set_test_environment": ["tests.conftest", "set_test_environment"],
    "shared_ldap_config": ["tests.conftest", "shared_ldap_config"],
    "shared_ldap_container": ["tests.conftest", "shared_ldap_container"],
    "sql": ["tests.e2e.conftest", "sql"],
    "t": ["tests.typings", "FlextDbtLdapTestTypes"],
    "table_exists": ["tests.e2e.conftest", "table_exists"],
    "test_dbt_services_sync": ["tests.unit.test_dbt_services_sync", ""],
    "test_dunder_alignment": ["tests.unit.test_version", "test_dunder_alignment"],
    "test_incremental_groups_sync_applies_bookmark_filter": [
        "tests.unit.test_version",
        "test_incremental_groups_sync_applies_bookmark_filter",
    ],
    "test_incremental_users_sync_applies_bookmark_filter": [
        "tests.unit.test_version",
        "test_incremental_users_sync_applies_bookmark_filter",
    ],
    "test_sync_users_uses_incremental_bookmark_and_persists_state": [
        "tests.unit.test_dbt_services_sync",
        "test_sync_users_uses_incremental_bookmark_and_persists_state",
    ],
    "test_version": ["tests.unit.test_version", ""],
    "test_version_metadata_integrity": [
        "tests.unit.test_version",
        "test_version_metadata_integrity",
    ],
    "test_version_properties": ["tests.unit.test_version", "test_version_properties"],
    "typings": ["tests.typings", ""],
    "u": ["tests.utilities", "FlextDbtLdapTestUtilities"],
    "unit": ["tests.unit", ""],
    "utilities": ["tests.utilities", ""],
    "x": ["flext_tests", "x"],
}

_EXPORTS: Sequence[str] = [
    "FlextDbtLdapTestConstants",
    "FlextDbtLdapTestModels",
    "FlextDbtLdapTestProtocols",
    "FlextDbtLdapTestTypes",
    "FlextDbtLdapTestUtilities",
    "MockLdapConnection",
    "MockLdapDbtAdapter",
    "POSTGRES_READY_MAX_RETRIES",
    "c",
    "conftest",
    "constants",
    "count_rows",
    "d",
    "db_connection",
    "dbt_ldap_macros",
    "dbt_ldap_models",
    "dbt_ldap_profile",
    "dbt_ldap_project_config",
    "dbt_ldap_sources",
    "dbt_ldap_tests",
    "dbt_profiles_dir",
    "dbt_project_dir",
    "e",
    "e2e",
    "flext_docker",
    "get_column_names",
    "h",
    "ldap_performance_config",
    "ldap_source_config",
    "ldap_validation_rules",
    "logger",
    "m",
    "mock_ldap_connection",
    "mock_ldap_dbt_adapter",
    "models",
    "p",
    "postgres_container",
    "project_root",
    "protocols",
    "psycopg",
    "pytest_configure",
    "query_database",
    "r",
    "run_dbt_command",
    "s",
    "sample_ldap_entries",
    "set_test_environment",
    "shared_ldap_config",
    "shared_ldap_container",
    "sql",
    "t",
    "table_exists",
    "test_dbt_services_sync",
    "test_dunder_alignment",
    "test_incremental_groups_sync_applies_bookmark_filter",
    "test_incremental_users_sync_applies_bookmark_filter",
    "test_sync_users_uses_incremental_bookmark_and_persists_state",
    "test_version",
    "test_version_metadata_integrity",
    "test_version_properties",
    "typings",
    "u",
    "unit",
    "utilities",
    "x",
]


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS, _EXPORTS)
